# Generated by Django 5.1.1 on 2024-09-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='livro_digital',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='livro',
            name='quantidade_total',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='livro',
            name='estoque',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
